title: Lintaraction
# author:
#   name: GitHub User
#   email: your-email@domain.com
description: Imai Laboratory Student-Alumni Meetup Party
copyright: (C) Lintaraction 2021. All Rights Researved

registration_url: https://forms.gle/11Cdd9wSCZL3RBPZA

minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
theme: minima

# plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
